version: '3.8'
services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345   # Replace with your root password
      MYSQL_DATABASE: mydatabase          # Replace with your desired database name
      MYSQL_USER: silver                    # Replace with your desired username
      MYSQL_PASSWORD: silver        # Replace with your desired password
    ports:
      - "3306:3306"                       # Exposes MySQL port
    volumes:
      - ./mysql_data:/var/lib/mysql       # Persist data on local storage
