_format_version: "3.0"
_transform: true

# Cấu hình các consumer
consumers:
  - username: SilverPham
    custom_id: SilverPham
    tags:
      - "[admin]"
    keyauth_credentials:
      - key: Spt3YHkVlg9dyViu4bPPnsyhrxNlwIiH
        ttl: 0
        tags:
          - "[admin]"
    acls:
      - group: SilverPham
        tags:
          - "[admin]"
  # Cấu hình các plugins
plugins:
  # Cấu hình authenciation gateway
  - name: key-auth
    enabled: true
    tags:
      - external-api
    config:
      key_in_query: true
      key_in_header: true
      key_names:
        - apikey
      anonymous:
      run_on_preflight: true
      hide_credentials: false
      key_in_body: false
    protocols:
      - http
      - https
  # Cấu hình điều khiển các Consumer được truy cập vào service
  - name: acl
    enabled: true
    tags:
      - "[external-api]"
    protocols:
      - http
      - https
    config:
      hide_groups_header: false
      deny: [ ]
      allow:
        - SilverPham
  # Cấu hình cache của request response
  - name: proxy-cache
    tags:
      - "[external-api]"
    protocols:
      - grpc
      - grpcs
      - http
      - https
    enabled: true
    config:
      memory:
        dictionary_name: kong_db_cache
      strategy: memory
      vary_headers:
      cache_ttl: 300
      cache_control: false
      response_code:
        - 200
        - 301
        - 404
      ignore_uri_case: false
      request_method:
        - GET
        - HEAD
      content_type:
        - text/plain
        - application/json
      storage_ttl:
      vary_query_params:
  # Cấu hình rate-limit của request
  - name: rate-limiting
    enabled: true
    tags:
      - "[external-api]"
    protocols:
      - http
      - https
    config:
      redis_timeout: 2000
      redis_host:
      path:
      hide_client_headers: true
      redis_server_name:
      redis_ssl_verify: false
      redis_username:
      limit_by: consumer
      redis_port: 6379
      redis_database: 0
      policy: local
      second:
      error_message: API rate limit exceeded
      error_code: 429
      header_name:
      redis_password:
      fault_tolerant: true
      minute:
      hour:
      day: 100000
      month:
      year:
      redis_ssl: false
  # Cấu hình chặn các IP address bên phía client
  - name: ip-restriction
    enabled: true
    tags:
      - "[external-api]"
    protocols:
      - http
      - https
    config:
      message:
      status: 409
      allow:
      deny:
        - 127.0.0.1
  # Cấu hình prometheus monitoring
  - name: prometheus
    enabled: true
    tags:
      - "[external-api]"
    protocols:
      - http
      - https
    config:
      bandwidth_metrics: true
      status_code_metrics: true
      per_consumer: true
      upstream_health_metrics: true
      latency_metrics: true
  # Cấu hình file ghi log
  - name: tcp-log
    enabled: true
    tags:
      - "[external-api]"
    protocols:
      - http
      - https
    config:
      host: 10.91.10.38 # địa chỉ của host logstash: 10.91.10.38
      port: 9301 # port đưa ra ngoài của docker
      timeout: 10000
      keepalive: 60000
      tls: false
      custom_fields_by_lua:
        app_name: app_name =  kong
# Cấu hình các Services và Routes
services:
  - name: mobile-shopping-api
    host: external-api-upstream
    enabled: true
    connect_timeout: 60000
    protocol: http
    read_timeout: 60000
    port: 8080
    retries: 5
    write_timeout: 60000
    tags:
      - "[external-api]"
    routes:
      - name: external-route
        paths:
          - /v1/api
        protocols:
          - http
          - https
        regex_priority: 0
        strip_path: true
        preserve_host: false
        request_buffering: true
        response_buffering: true
        https_redirect_status_code: 426
        path_handling: v0
        tags:
          - "[external-api]"
upstreams:
  - name: external-api-upstream
    hash_on: none
    hash_on_cookie_path: /
    healthchecks:
      threshold: 0
      passive:
        unhealthy:
          http_statuses:
            - 429
            - 500
            - 503
          tcp_failures: 0
          timeouts: 5
          http_failures: 5
        type: http
        healthy:
          successes: 80
          http_statuses:
            - 200
            - 201
            - 202
            - 203
            - 204
            - 205
            - 206
            - 207
            - 208
            - 226
            - 300
            - 301
            - 302
            - 303
            - 304
            - 305
            - 306
            - 307
            - 308
      active:
        healthy:
          successes: 5
          interval: 100
          http_statuses:
            - 200
            - 302
        unhealthy:
          http_statuses:
            - 429
            - 404
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
          interval: 100
          tcp_failures: 0
          timeouts: 0
          http_failures: 5
        concurrency: 10
        http_path: /actuator/health
        timeout: 1
        type: http
        https_verify_certificate: true
    hash_fallback: none
    algorithm: round-robin
    slots: 5000
    tags:
      - "[external-api]"
    host_header: external-api-upstream
    targets:
      - target: 10.91.10.38:8080
        tags:
          - "[external-api]"
        weight: 100


